# Generated by Django 5.1.5 on 2025-07-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mother",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("fathers_name", models.CharField(max_length=100)),
                (
                    "age_category",
                    models.CharField(
                        choices=[
                            ("under_18_or_over_35", "<18 yoki >35 yosh"),
                            ("between_18_and_35", "18–35 yosh"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bmi_category",
                    models.CharField(
                        choices=[
                            ("ozgin", "<18.5 (Ozg‘inlik)"),
                            ("normal", "18.5–24.9 (Normal)"),
                            ("semiz", "≥25 (Ortiqcha vazn)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("oliy", "Oliy"),
                            ("orta_maxsus", "O‘rta maxsus"),
                            ("orta", "O‘rta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "income_level",
                    models.CharField(
                        choices=[
                            ("yuqori", "Yuqori daromad"),
                            ("ortacha", "O‘rtacha daromad"),
                            ("past", "Past daromad (eng kam ish haqi)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_chronic_illness", models.BooleanField()),
                ("harmful_habits", models.BooleanField()),
                (
                    "knowledge_level",
                    models.CharField(
                        choices=[
                            ("yoq", "Umuman yo‘q"),
                            ("qisman", "Qisman biladi"),
                            (
                                "bor",
                                "Biladi (gigiena, ovqatlantirish, g‘amxo‘rlik va h.k.)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mood_last_2_weeks",
                    models.CharField(
                        choices=[
                            ("doimiy_tushkun", "Doimo tushkun"),
                            ("baʼzan_tushkun", "Ba’zan tushkun"),
                            ("yoq", "Tushkunlik yo‘q"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField()),
                ("birth_weight", models.FloatField()),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="anketa.mother",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnketaResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_type",
                    models.CharField(
                        choices=[
                            ("tabiiy", "Tabiiy tug‘ruq"),
                            ("kesarcha", "Kesarcha kesish"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "took_vitamins",
                    models.CharField(
                        choices=[
                            ("olmagan", "Umuman olmagan"),
                            ("qisman", "Qisman olgan (faqat 3 oy)"),
                            ("muntazam", "Muntazam olgan (9 oy)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pregnancy_complications", models.BooleanField()),
                ("delivery_complications", models.BooleanField()),
                (
                    "contact_after_birth",
                    models.CharField(
                        choices=[
                            ("darhol", "Tug‘ruqdan so‘ng darhol birga bo‘lgan"),
                            ("24_soatdan_keyin", "24 soatdan keyin birga bo‘lgan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "breastfeeding",
                    models.CharField(
                        choices=[
                            ("umuman_emizmagan", "Umuman emizmagan"),
                            ("aralash", "Aralash"),
                            ("faqat_ona_suti", "Faqat ona suti"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breastfeeding_difficulties", models.BooleanField()),
                (
                    "complementary_feeding_time",
                    models.CharField(
                        choices=[
                            ("6_oydan_keyin", "6 oydan keyin"),
                            ("noto‘g‘ri_vaqt", "<6 yoki 6-oyda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "risk_category",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="anketa.child"
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anketa_responses",
                        to="anketa.mother",
                    ),
                ),
            ],
        ),
    ]
