# Generated by Django 5.1.5 on 2025-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anketa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mother",
            name="address",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mother",
            name="passport_number",
            field=models.CharField(default=8888888, max_length=50),
            preserve_default=False,
        ),
    ]
