# Generated by Django 5.1.5 on 2025-08-12 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anketa", "0002_mother_address_mother_passport_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anketaresponse",
            name="complementary_feeding_time",
            field=models.CharField(
                choices=[("6_oydan_keyin", "6 oydan keyin"), ("noto‘g‘ri_vaqt", "<6")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mother",
            name="address",
            field=models.TextField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="Manzilni ko'cha nomi va uy raqami shaklda yozing (masalan, Namozgoh 15).",
                        regex="^[A-Za-zÆØÅæøå\\-\\.\\s]+\\s+\\d+[A-Za-zÆØÅæøå]?$",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mother",
            name="passport_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Passport raqami 2 katta harf va undan so'ng 7 ta raqam bilan davom etgan bo'lishi kerak (masalan, HA1234567).",
                        regex="^[A-Z]{2}\\d{8}$",
                    )
                ],
            ),
        ),
    ]
