# Generated by Django 5.1.5 on 2025-08-12 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anketa", "0003_alter_anketaresponse_complementary_feeding_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mother",
            name="passport_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Passport raqami 2 katta harf va undan so'ng 7 ta raqam bilan davom etgan bo'lishi kerak (masalan, HA1234567).",
                        regex="^[A-Z]{2}\\d{7}$",
                    )
                ],
            ),
        ),
    ]
